apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: analyse-oel-frontend
spec:
  project: default
  source:
    repoURL: https://github.com/Colas-Lepoutre/Analyse-OEL_deployment.git
    targetRevision: main
    path: deployment_front
  destination:
    server: https://kubernetes.default.svc
    namespace: user-colaslepoutre
  syncPolicy:
    automated:
      selfHeal: true
