apiVersion: apps/v1
kind: Deployment
metadata:
  name: analyse-oel-front-deployment
  labels:
    app: analyse-oel-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analyse-oel-front
  template:
    metadata:
      labels:
        app: analyse-oel-front
    spec:
      containers:
      - name: analyse-oel-front
        image: colaslepoutre/analyse-oel_front:test
        imagePullPolicy: Always
        ports:
        - containerPort: 8501
