apiVersion: v1
kind: Service
metadata:
  name: analyse-oel-front-service
spec:
  type: LoadBalancer
  selector:
    app: analyse-oel-front
  ports:
    - name: analyse-oel-front-port
      protocol: TCP
      port: 8
      targetPort: 8501
