apiVersion: apps/v1
kind: Deployment
metadata:
  name: analyse-oel-deployment
  labels:
    app: analyse-oel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analyse-oel
  template:
    metadata:
      labels:
        app: analyse-oel
    spec:
      containers:
      - name: analyse-oel
        image: colaslepoutre/analyse-oel:v2.0
        ports:
        - containerPort: 8000
        env:
                - name: API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: api-jeton
                      key: API_KEY
                      
