apiVersion: apps/v1
kind: Deployment
metadata:
  name: analyse-oel-deployment
  labels:
    app: analyse-oel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analyse-oel
  template:
    metadata:
      labels:
        app: analyse-oel
    spec:
      containers:
      - name: analyse-oel
        image: colaslepoutre/analyse-oel:sha-0b9cb74
        ports:
        - containerPort: 8000
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: analyse-oel-secrets
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: analyse-oel-secrets
              key: AWS_SECRET_ACCESS_KEY
        - name: API_KEY
            valueFrom:
              secretKeyRef:
                name: analyse-oel-secrets
                key: API_KEY
  
